name: troll_camera
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.2

dev_dependencies:
  blackfoot_flutter_lint: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
